// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ConnectWalletJsx from "./ConnectWallet.jsx";

var make = ConnectWalletJsx.ConnectWallet;

var ConnectWallet = {
  make: make
};

function ConnectWalletWrapper(Props) {
  return React.createElement("div", undefined, React.createElement(make, {}));
}

var make$1 = ConnectWalletWrapper;

export {
  ConnectWallet ,
  make$1 as make,
  
}
/* make Not a pure module */
